### ISSUE TITLE
Wordsmithing

### ISSUE THREAD

**Issue by kafoster** [jdcalus/STSA-Workshop-3-Hybrid-Cloud#1]
I would change this:
Using a ReST client is typically done by specifying the HTTP directive (a GET, which typically requests information, for example) and an address, like this:

to this:
Using a ReST client is typically done by specifying the HTTP directive (a GET, for example, which  requests information) and an address, like this:

fixed (jdcalus)

**Comment by kafoster** [comment]
You have a screen capture of the Import that is different from what I saw.  Mine was titled, Import nodes.  I didn't see anything about exporting (yet.)

fixed (jdcalus)

**Comment by kafoster** [comment]
After this:
Now click on the Deploy button at the top of the screen. You can now click on the left side of the "Hello World" and you should see the output in the debug panel 

You might have the screen cap include the tabs in the right panel (info, debug) and show the debug tab in the foreground)

I didn't fix this, because the top tabs of show conflicting information, so I left them out. (jdcalus)

**Comment by kafoster** [comment]
At the end of ex 1 when adding the URL to the Store Lookup, you might want to tell folks to "Deploy"  This was required to get the right result (at least in my case.)

fixed (jdcalus)

**Comment by kafoster** [comment]
This:
As you can see in the image below where are two conditions in he "switch node". 

Should be:
As you can see in the image below there are two conditions in the "switch node". 

fixed (jdcalus)

**Comment by kafoster** [comment]
Next, click on the left side of the Inject node that has "19645922". This causes the inject to be fired and the flow to be executed.

You might mention that folks should check their debug node to ensure it is activated.  (Mine wasn't)

fixed (jdcalus)

**Comment by kafoster** [comment]
The words Architecture Overview are in exercise 2 around the "parse name" part of the exercise.  I saw two of them mixed in with the instructions.  I'm thinking they are not supposed to be there.

fixed (jdcalus)

**Comment by kafoster** [comment]
This:
Click ont he tile to create the service

Should be this:
Click on the tile to create the service

fixed (jdcalus)

**Comment by kafoster** [comment]
This "http request" node is calling the weather.com API to locate geo coordinates for a city. In our case, the city name is "Dallas". 

It looks like the Inject node is using Des Moines for the city.  Did you mean for the user to change this to Dallas?  (Or am I mis-reading this part of the exercise)

**Comment by kafoster** [comment]
I'm not following this:
With your credentials entered, you should be able to access a web page by heading to [name].mybluemix.net/weather.

I added a name to the 48 hour http request node (48hour) and executed the following URL in a new browser tab:
48hour.mybluemix.net/weather

I got a 404 not found.  Maybe I should have initiated the URL from the NodeRed session??

It is the application name for the NodeRed application that was created. So something like STSAWorkshop-xxx

fixed (jdcalus)

**Comment by jdcalus** [comment]
Updated all of the items. Thanks for the help Kim!
